// <auto-generated />
using System;
using Fiap.Banco.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Banco.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506154616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Banco.API.Models.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAgencia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.HasKey("Id");

                    b.HasIndex("IdAgencia");

                    b.ToTable("Clientes");

                    b.HasDiscriminator<string>("Tipo").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Contratacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdProduto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("observacao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdProduto");

                    b.ToTable("Contratacoes");
                });

            modelBuilder.Entity("Fiap.Banco.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<string>("TipoProduto").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.PessoaFisica", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Cliente");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.PessoaJuridica", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Cliente");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("NVARCHAR2(180)");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.ReceberSalario", b =>
                {
                    b.HasBaseType("Fiap.Banco.Api.Models.Produto");

                    b.Property<int>("ConvenioAtivo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EmpresaConveniada")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasDiscriminator().HasValue("ReceberSalario");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Nome = "Receber Salário",
                            ConvenioAtivo = 0,
                            EmpresaConveniada = ""
                        });
                });

            modelBuilder.Entity("Fiap.Banco.Api.Models.Emprestimo", b =>
                {
                    b.HasBaseType("Fiap.Banco.Api.Models.Produto");

                    b.Property<int>("Parcelas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TaxaJuros")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasDiscriminator().HasValue("Emprestimo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Empréstimo",
                            Parcelas = 0,
                            TaxaJuros = 0m,
                            Valor = 0m
                        });
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Cliente", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Agencia", "Agencia")
                        .WithMany("Clientes")
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Contratacao", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Cliente", "Cliente")
                        .WithMany("Contratacoes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fiap.Banco.Api.Models.Produto", "Produto")
                        .WithMany("Contratacoes")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Agencia", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Cliente", b =>
                {
                    b.Navigation("Contratacoes");
                });

            modelBuilder.Entity("Fiap.Banco.Api.Models.Produto", b =>
                {
                    b.Navigation("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
